#!/bin/sh

# Can't access service without login.
curl -i -H "Authorization: bearer kaka" http://localhost:4567/api/secret

# Log in
INFO=`curl -s -X POST http://localhost:4567/oath/token -d '{"user":"test", "password":"test"}'`
ACCESS_TOKEN=`echo $INFO | jq -r .access_token`

# Use token to access service.
curl -i -H "Authorization: bearer $ACCESS_TOKEN" http://localhost:4567/api/secret
